# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

I have imported the three important libraries for this project.
1) The numpy libraries which will allow us to work with 2-D arrays.
2) The pandas array which will help us import the dataset.
3) The tensorflow library which will help us create the Artificial Neural Network.

In [2]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
data = pd.read_excel('Folds5x2_pp.xlsx')
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

1)I have imported the Excel file using the pandas lirary.
2)I have seperated the X and the y variable of the dataset using the 'iloc' method of the pandas library.
3)The last column is the dependent variable and therefore is the y variable and I have accordingly indexed it.

In [4]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

I have split the training and the testing data set using the class train_test_split of the sklearn library.(One of the best library for Machine learning). The test size means the amount of testing data from the total data. I have selected a random_state just so that the results match.

## Part 2 - Building the ANN

### Initializing the ANN

In [7]:
ann = tf.keras.models.Sequential()

I have defined a variable called 'ann' which is the variale for the artificial neural ntowrk and as we are making a Sequential neural network I have called the instance Sequential from the tensorflow library. 

Two types of Ann 1) Sequential and 2) Computational Graph

### Adding the input layer and the first hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Here we use the add function of the Sequential module and add a Dense layer which means a fully connected layer and with 6 neurons and with an activation function called the Rectified linear Unit. The above added layer is he first layer in our artificial neural network.

### Adding the second hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Here we input the same statement and add the second layer to the ANN with the same number of units/neurons and also the same activation function.

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 1))

Here we add the final layer which is the output layer which consist of only  1 neuron which tells us the final energy output of the plant.

## Part 3 - Training the ANN

### Compiling the ANN

In [11]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

Here we compile the entire ANN with the compile function of the Sequential module. The optimizer used here is 'adam' which is for the stochastic gradient descent which is used to change the weight of the synapse after the backpropagation. The loss function here is the mean squared error which is the summation of the square of the Predicted value minus the Original Value. This loss function should be minimzed to make ourr neural network more optimum.

### Training the ANN model on the Training set

In [12]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 2ms/step - loss: 3876.3965
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 182.0883
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 171.7133
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 159.0837
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 145.3277
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 130.3996
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 115.2526
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 100.4807
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 86.6053
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 74.1402
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 62.8409
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - loss: 

Here we use the predict function to predict and train our neural network on the training set. The batch_size is the nubr of batches in which the data will be grouped and processed in the same time. The number of epochs is the number of time backpropogation will take place in the neural network and the times it will change the weights.

### Predicting the results of the Test set

In [13]:
pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((pred.reshape(len(pred),1), y_test.reshape(len(y_test),1)), 1))

[[433.66 431.23]
 [464.83 460.01]
 [468.35 461.14]
 ...
 [475.58 473.26]
 [442.29 438.  ]
 [461.54 463.28]]


Here have predicted the test values using the predictt function and using the X_test values as the paramenter. The printoptions allows us to specify the number of decimal places in the numpy array. 